name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build da Aplicação

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Criar .env com banco fake
      run: |
        echo "DATABASE_URL=sqlite:///:memory:" > .env

    - name: Instalando dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build fake
      run: echo "Aqui rodaria o processo de build real, se existisse"

    - name: Rodar API (exemplo, só pra teste)
      run: timeout 10 uvicorn main:app --host 0.0.0.0 --port 8000 || true

  unit-tests:
    runs-on: ubuntu-latest
    name: Testes Unitários

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Criar .env com banco fake
      run: echo "DATABASE_URL=sqlite:///:memory:" > .env

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalando dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar testes
      run: pytest tests/testUnitario/ -v

  notification:
    needs: unit-tests
    runs-on: ubuntu-latest
    name: Notificação de Testes

    env:
      DESTINATION_EMAIL: ${{ vars.DESTINATION_EMAIL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Notification
      run: sh scripts/shell.sh